version: '3.8'

services:
  dev-build:
    image: nginx:alpine
    container_name: dev-build
    ports:
      - "8080:80"
    volumes:
      - ./dist/browser/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  surrealdb:
    image: kennycallado/q-api-store:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    command:
      - -A
      # - --no-banner
      # - --log=trace
      # - --log=info
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  auth:
    image: kennycallado/q-api-super:latest
    container_name: auth
    environment:
      ROCKET_DATABASES: '{store={host="surrealdb", port=8000, username="root", password="root"}}'
      ROCKET_SECRET_KEY: ''
    ports:
      - "9000:8080"
